#!/usr/bin/env node
// Builds web/src/generated/{content,tours,demos}.ts from ../docs/*.md and ../demos/<name>/.
// Pure Node + marked; run from web/ as `npm run content` (any cwd works — paths are script-relative).
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from 'node:fs';
import { join, dirname, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const here = dirname(fileURLToPath(import.meta.url));
const webDir = join(here, '..');
const repoDir = join(webDir, '..');
const docsDir = join(repoDir, 'docs');
const demosDir = join(repoDir, 'demos');
const outDir = join(webDir, 'src', 'generated');

marked.use({ gfm: true, breaks: false });

/** First `# ` heading of a Markdown document, or the fallback. */
function titleOf(md, fallback) {
  for (const line of md.split(/\r?\n/)) {
    const m = /^#\s+(.+?)\s*#*\s*$/.exec(line);
    if (m) return m[1].trim();
  }
  return fallback;
}

/** GitHub-style anchor slug for a heading. */
function anchorSlug(text) {
  return text
    .toLowerCase()
    .replace(/<[^>]+>/g, '')
    .replace(/&[a-z]+;|&#\d+;/g, '')
    .replace(/[^a-z0-9 \-_]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

/** Post-process rendered HTML: heading ids, .md links → hash routes, tables scroll. */
function polish(html) {
  const seen = new Map();
  html = html.replace(/<h([1-6])>([\s\S]*?)<\/h\1>/g, (all, level, inner) => {
    let id = anchorSlug(inner) || 'section';
    const n = seen.get(id) ?? 0;
    seen.set(id, n + 1);
    if (n > 0) id = `${id}-${n}`;
    return `<h${level} id="${id}">${inner}</h${level}>`;
  });
  // docs/foo.md → #/foo ; demos/name/README.md → #/demos/name ; ../demos/name/README.md too.
  html = html.replace(/href="([^"]+)"/g, (all, href) => {
    if (/^[a-z]+:/.test(href) || href.startsWith('#') || href.startsWith('/')) return all;
    let m = /^(?:\.\.\/)*demos\/([A-Za-z0-9_-]+)\/README\.md(#.*)?$/.exec(href);
    if (m) return `href="#/demos/${m[1]}"`;
    m = /^(?:\.\.\/)*(?:docs\/)?([A-Za-z0-9_-]+)\.md(#.*)?$/.exec(href);
    if (m) return `href="#/${m[1]}"`;
    return all;
  });
  html = html.replace(/<table>/g, '<div class="table-scroll"><table>').replace(/<\/table>/g, '</table></div>');
  return html;
}

function render(md) {
  const out = marked.parse(md);
  return polish(typeof out === 'string' ? out : String(out));
}

function listDir(dir) {
  return existsSync(dir) ? readdirSync(dir).sort() : [];
}

const content = {};
const tours = {};
const demoFiles = {};

for (const file of listDir(docsDir)) {
  if (extname(file) !== '.md') continue;
  const slug = basename(file, '.md');
  const md = readFileSync(join(docsDir, file), 'utf8');
  content[slug] = { title: titleOf(md, slug), html: render(md) };
}

for (const name of listDir(demosDir)) {
  const dir = join(demosDir, name);
  if (!statSync(dir).isDirectory()) continue;
  const readme = join(dir, 'README.md');
  if (existsSync(readme)) {
    const md = readFileSync(readme, 'utf8');
    content[`demos/${name}`] = { title: titleOf(md, name), html: render(md) };
  }
  const tourPath = join(dir, 'tour.json');
  if (existsSync(tourPath)) {
    try {
      const raw = JSON.parse(readFileSync(tourPath, 'utf8'));
      if (Array.isArray(raw)) {
        tours[name] = raw
          .filter((s) => s && typeof s === 'object')
          .map((s) => ({ panel: String(s.panel ?? ''), text: String(s.text ?? '') }));
      }
    } catch (e) {
      console.warn(`build-content: skipping ${tourPath}: ${e.message}`);
    }
  }
  const files = [];
  for (const f of listDir(dir)) {
    if (f === 'README.md' || f === 'tour.json' || f.endsWith('.expected')) continue;
    const p = join(dir, f);
    if (!statSync(p).isFile()) continue;
    files.push({ name: f, text: readFileSync(p, 'utf8') });
  }
  demoFiles[name] = files;
}

mkdirSync(outDir, { recursive: true });

const banner = '// Generated by scripts/build-content.mjs — do not edit.\n';
writeFileSync(
  join(outDir, 'content.ts'),
  `${banner}export const CONTENT: Record<string, { title: string; html: string }> = ${JSON.stringify(content, null, 2)};\n`,
);
writeFileSync(
  join(outDir, 'tours.ts'),
  `${banner}export const TOURS: Record<string, { panel: string; text: string }[]> = ${JSON.stringify(tours, null, 2)};\n`,
);
writeFileSync(
  join(outDir, 'demos.ts'),
  `${banner}export const DEMO_FILES: Record<string, { name: string; text: string }[]> = ${JSON.stringify(demoFiles, null, 2)};\n`,
);

const nDocs = Object.keys(content).length;
const nDemos = Object.keys(demoFiles).length;
console.log(`build-content: ${nDocs} pages, ${nDemos} demos, ${Object.keys(tours).length} tours -> ${outDir}`);
