#ifndef TURINGOS_HAL_H
#define TURINGOS_HAL_H
/* Host abstraction layer — the machine's ONLY door to the outside world.
 * Two implementations: hal_posix.c (native) and hal_wasm.c (Emscripten).
 * No file under src/{emu,bios,kernel,fs,compiler,lang,api} may include <stdio.h>. */
#include <stdint.h>

void     hal_init(void);                 /* posix: raw tty if stdin is a TTY and option raw!=0 */
void     hal_shutdown(void);             /* posix: restore terminal */
int      hal_set_option(const char *key, const char *value);   /* 0 ok, -1 unknown key */
/* posix option keys: "disk_a" "disk_b" (image paths), "shell" (path overriding the embedded blob),
 * "snap_dir" (directory; enables hal_snapshot), "fps" (frames/s for hal_vsync, default 60),
 * "raw" ("0"/"1", default auto), "display" ("0"/"1": render framebuffer to the TTY on vsync),
 * "stdin_script" (path whose bytes are fed as console input, then EOF).
 * wasm: every key returns -1. */

/* Console */
void     hal_con_out(uint8_t ch);
int      hal_con_in_ready(void);         /* 1 if hal_con_in() would return a byte or EOF now */
int      hal_con_in(void);               /* 0..255, -1 = nothing available, -2 = EOF */
int      hal_con_push(uint8_t ch);       /* inject a byte into the console input queue (both HALs); 0 ok, -1 full */

/* Keys */
uint8_t  hal_keys(void);                 /* TOS_KEY_* bitmask, non-blocking */
void     hal_keys_set(uint8_t mask);     /* host sets the mask (wasm: from JS; posix: merged with TTY keys) */

/* Time / frames */
uint32_t hal_time_ms(void);
void     hal_vsync(void);                /* posix: sleep to the next 1/fps boundary; wasm: no-op */

/* Disk images (whole-image load/save; the fs keeps images in static buffers) */
int      hal_disk_load(uint8_t disk, uint8_t *buf, uint32_t cap);        /* bytes loaded, 0 = no image */
int      hal_disk_save(uint8_t disk, const uint8_t *buf, uint32_t len);  /* 0 ok, -1 error */

/* Shell binary: build/gen/shell_blob.c defines these (generated by tools/bin2c from build/bin/shell.com) */
extern const uint8_t  tos_shell_blob[];
extern const uint32_t tos_shell_blob_len;
int      hal_shell_blob(const uint8_t **ptr, uint32_t *len);   /* 0 ok, -1 unavailable */

/* Observation hooks */
void     hal_snapshot(const uint8_t *tape, uint32_t tape_len, const uint8_t *meta, uint32_t meta_len);
void     hal_display(const uint8_t *fb);   /* 256-byte framebuffer; posix renders with ANSI half-blocks when display=1 */

#endif
